### ISSUE TITLE
Two shares not pulling down data

### ISSUE THREAD

**Issue by R7914T** [cmallwitz/Financials-Extension#24]
I am having problems with 2 shares and  one ETF that will not bring down the data into a Libreoffice SS. Can you please look at why this is happening:

1. BATM andvanced Comms: LSE BVC 
My call entered as =GETREALTIME($B12,"prev_close","ft")
Note: B12=BVC

(error message #N/A)

2. NORTHERN DYNASTY MINERALS LTD COM
Per Web address: quote on NYSE with code  NAK. I checked with NYSE web site.
My call entered as =GETREALTIME("NYQ:NDM:","prev_close","ft") 
Error message =#N/A

ETF
I have an etf  from Invesco under the epic of SSLV. Is there a way of pulling down its price?
For more detail about the ways of describing the ETF see  https://etf.invesco.com/gb/private/en/product/invesco-physical-silver-etc/trading-information
The etf is quoted on the LSE in $
Call entered as =GETREALTIME($B26,"prev_close","ft")
B26 = SSLV
Error = #N/A

Also How do I get the exchange rate for dollars to pounds in the SS automatically?

**Comment by cmallwitz** [comment]
Could you check your symbols are correct (as referenced from other cells)?

- I can see BVC:LSE
- I only find NDM as NDM:TOR but not on NYQ
- and SSLV as SSLV:LSE:USD

(All on FT web site)

**Comment by R7914T** [comment]
I think I have found the cause in that if I substitute the middle part of the expression with 21 they work.  Keeping it at "prev_close" does not appear to work in the complex location codes that went wrong for me. I hope you will be able to now easily find the underlying cause.

**Comment by cmallwitz** [comment]
Maybe I should look into using lower case names for these data points

**Comment by cmallwitz** [comment]
OK, nothing wrong with using lower case names to specify the code for the data point but
- 21 is "LAST_PRICE" / "last_price"
- "prev_close" is 5

LAST_PRICE works for me with BVC:LSE NDM:TOR SSLV:LSE:USD
PREV_CLOSE works for me with BVC:LSE NDM:TOR but not with SSLV:LSE:USD

Looking at "https://markets.ft.com/data/etfs/tearsheet/summary?s=SSLV:LSE:USD" it seems open/close/prev_close/etc is missing for ETFs (same problem for other ETFs I checked).

Please note: when trying the above I happened to use single instead of double quotes ('last_price' vs "last_price") - Open Calc doesn't seem to handle single quotes (this is not an issue with the extension itself which is not even called) - so please make sure you use double quotes.

Otherwise I can't see anything wrong...
