### ISSUE TITLE
Extension cannot be enabled in Ubuntu 22.04 Libreoffice 7.3.5.2

### ISSUE THREAD

**Issue by klausi** [cmallwitz/Financials-Extension#61]
My Libreoffice kept crashing when opening any files (I had this extension installed previously). So I decided to nuke my Libreoffice config with this extension with `rm -rf ~/.config/libreoffice/` and tried to install this extension again. That does not work now with the following error:

![image](https://user-images.githubusercontent.com/213229/188331352-f64f161f-8add-4080-a26a-353708577492.png)
Any ideas on that?

**Comment by cmallwitz** [comment]
Not sure what the error tries to tell us...

I tried using the extension on a fresh Ubuntu 22.04 / LibreOffice 7.3.5.2 and that seems to work. Then I removed the ~/.config/libreoffice/ too. Afterwards the extension is gone from LO but I had no issues reinstalling and using it again. The error message seems to be in the LO side rather than from the extension itself. 

So no idea!

**Comment by klausi** [comment]
Thanks - I also tested on a fresh Ubuntu 22.04 virtual machine, there the extension worked normally for me as well.

It seems like I have some combination of additional programs installed or home directory configuration that breaks the APT version of Libreoffice in the Ubuntu sources.

I switched to the Snap version of LibreOffice now and there the extension works normally. The Snap version is much slower on startup because Snap is inferior to native APT packages performance-wise because of their slow virtual filesystem. That is still an acceptable workaround for me for now.

Closing this issue.
